import { Currency } from '@/types';

export const CURRENCIES: Currency[] = [
  { code: 'PKR', symbol: 'Rs', name: 'Pakistani Rupee', symbolPosition: 'before' },
  { code: 'USD', symbol: '$', name: 'US Dollar', symbolPosition: 'before' },
  { code: 'EUR', symbol: '€', name: 'Euro', symbolPosition: 'before' },
  { code: 'GBP', symbol: '£', name: 'British Pound', symbolPosition: 'before' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', symbolPosition: 'before' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', symbolPosition: 'before' },
  { code: 'SAR', symbol: 'ر.س', name: 'Saudi Riyal', symbolPosition: 'before' },
  { code: 'TRY', symbol: '₺', name: 'Turkish Lira', symbolPosition: 'before' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', symbolPosition: 'before' },
  { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', symbolPosition: 'before' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won', symbolPosition: 'before' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar', symbolPosition: 'before' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', symbolPosition: 'before' },
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', symbolPosition: 'before' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', symbolPosition: 'before' },
  { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', symbolPosition: 'before' },
  { code: 'PHP', symbol: '₱', name: 'Philippine Peso', symbolPosition: 'before' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht', symbolPosition: 'before' },
  { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', symbolPosition: 'before' },
  { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', symbolPosition: 'before' },
  { code: 'ZAR', symbol: 'R', name: 'South African Rand', symbolPosition: 'before' },
  { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', symbolPosition: 'before' },
  { code: 'QAR', symbol: 'ر.ق', name: 'Qatari Riyal', symbolPosition: 'before' },
  { code: 'BHD', symbol: 'BD', name: 'Bahraini Dinar', symbolPosition: 'before' },
  { code: 'OMR', symbol: 'ر.ع', name: 'Omani Rial', symbolPosition: 'before' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', symbolPosition: 'before' },
  { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', symbolPosition: 'after' },
  { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', symbolPosition: 'after' },
  { code: 'DKK', symbol: 'kr', name: 'Danish Krone', symbolPosition: 'after' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', symbolPosition: 'before' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', symbolPosition: 'before' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', symbolPosition: 'before' },
  { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', symbolPosition: 'before' },
  { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso', symbolPosition: 'before' },
  { code: 'COP', symbol: 'COL$', name: 'Colombian Peso', symbolPosition: 'before' },
  { code: 'ARS', symbol: 'AR$', name: 'Argentine Peso', symbolPosition: 'before' },
  { code: 'CLP', symbol: 'CL$', name: 'Chilean Peso', symbolPosition: 'before' },
  { code: 'PEN', symbol: 'S/', name: 'Peruvian Sol', symbolPosition: 'before' },
  { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', symbolPosition: 'after' },
  { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', symbolPosition: 'before' },
  { code: 'NPR', symbol: 'Rs', name: 'Nepalese Rupee', symbolPosition: 'before' },
  { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', symbolPosition: 'before' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', symbolPosition: 'before' },
  { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', symbolPosition: 'before' },
  { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', symbolPosition: 'before' },
  { code: 'JOD', symbol: 'JD', name: 'Jordanian Dinar', symbolPosition: 'before' },
  { code: 'LBP', symbol: 'L£', name: 'Lebanese Pound', symbolPosition: 'before' },
  { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham', symbolPosition: 'before' },
  { code: 'RUB', symbol: '₽', name: 'Russian Ruble', symbolPosition: 'after' },
  { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', symbolPosition: 'before' },
  { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', symbolPosition: 'after' },
  { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', symbolPosition: 'after' },
  { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', symbolPosition: 'after' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu', symbolPosition: 'after' },
  { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', symbolPosition: 'after' },
  { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', symbolPosition: 'after' },
  { code: 'RSD', symbol: 'din', name: 'Serbian Dinar', symbolPosition: 'after' },
  { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', symbolPosition: 'after' },
  { code: 'TWD', symbol: 'NT$', name: 'Taiwan Dollar', symbolPosition: 'before' },
  { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', symbolPosition: 'before' },
];
